<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NationaliteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::insert("INSERT INTO `nationalites` (`alpha_2_code`, `alpha_3_code`, `en_short_name`, `name`) VALUES
                ( 'MA', 'MAR', 'Morocco', 'Moroccan'),
                ( 'AF', 'AFG', 'Afghanistan', 'Afghan'),
                ( 'AX', 'ALA', 'Åland Islands', 'Åland Island'),
                ( 'AL', 'ALB', 'Albania', 'Albanian'),
                ( 'DZ', 'DZA', 'Algeria', 'Algerian'),
                ( 'AS', 'ASM', 'American Samoa', 'American Samoan'),
                ( 'AD', 'AND', 'Andorra', 'Andorran'),
                ( 'AO', 'AGO', 'Angola', 'Angolan'),
                ( 'AI', 'AIA', 'Anguilla', 'Anguillan'),
                ( 'AQ', 'ATA', 'Antarctica', 'Antarctic'),
                ( 'AG', 'ATG', 'Antigua and Barbuda', 'Antiguan or Barbudan'),
                ( 'AR', 'ARG', 'Argentina', 'Argentine'),
                ( 'AM', 'ARM', 'Armenia', 'Armenian'),
                ( 'AW', 'ABW', 'Aruba', 'Aruban'),
                ( 'AU', 'AUS', 'Australia', 'Australian'),
                ( 'AT', 'AUT', 'Austria', 'Austrian'),
                ( 'AZ', 'AZE', 'Azerbaijan', 'Azerbaijani Azeri'),
                ( 'BS', 'BHS', 'Bahamas', 'Bahamian'),
                ( 'BH', 'BHR', 'Bahrain', 'Bahraini'),
                ( 'BD', 'BGD', 'Bangladesh', 'Bangladeshi'),
                ( 'BB', 'BRB', 'Barbados', 'Barbadian'),
                ( 'BY', 'BLR', 'Belarus', 'Belarusian'),
                ( 'BE', 'BEL', 'Belgium', 'Belgian'),
                ( 'BZ', 'BLZ', 'Belize', 'Belizean'),
                ( 'BJ', 'BEN', 'Benin', 'Beninese, Beninois'),
                ( 'BM', 'BMU', 'Bermuda', 'Bermudian, Bermudan'),
                ( 'BT', 'BTN', 'Bhutan', 'Bhutanese'),
                ( 'BO', 'BOL', 'Bolivia (Plurinational State of)', 'Bolivian'),
                ( 'BQ', 'BES', 'Bonaire Sint Eustatius and Saba', 'Bonaire'),
                ( 'BA', 'BIH', 'Bosnia and Herzegovina', 'Bosnian or Herzegovinian'),
                ( 'BW', 'BWA', 'Botswana', 'Motswana Botswanan'),
                ( 'BV', 'BVT', 'Bouvet Island', 'Bouvet Island'),
                ( 'BR', 'BRA', 'Brazil', 'Brazilian'),
                ( 'IO', 'IOT', 'British Indian Ocean Territory', 'BIOT'),
                ( 'BN', 'BRN', 'Brunei Darussalam', 'Bruneian'),
                ( 'BG', 'BGR', 'Bulgaria', 'Bulgarian'),
                ( 'BF', 'BFA', 'Burkina Faso', 'Burkinabé'),
                ( 'BI', 'BDI', 'Burundi', 'Burundian'),
                ( 'CV', 'CPV', 'Cabo Verde', 'Cabo Verdean'),
                ( 'KH', 'KHM', 'Cambodia', 'Cambodian'),
                ( 'CM', 'CMR', 'Cameroon', 'Cameroonian'),
                ( 'CA', 'CAN', 'Canada', 'Canadian'),
                ( 'KY', 'CYM', 'Cayman Islands', 'Caymanian'),
                ( 'CF', 'CAF', 'Central African Republic', 'Central African'),
                ( 'TD', 'TCD', 'Chad', 'Chadian'),
                ( 'CL', 'CHL', 'Chile', 'Chilean'),
                ( 'CN', 'CHN', 'China', 'Chinese'),
                ( 'CX', 'CXR', 'Christmas Island', 'Christmas Island'),
                ( 'CC', 'CCK', 'Cocos (Keeling) Islands', 'Cocos Island'),
                ( 'CO', 'COL', 'Colombia', 'Colombian'),
                ( 'KM', 'COM', 'Comoros', 'Comoran Comorian'),
                ( 'CG', 'COG', 'Congo (Republic of the)', 'Congolese'),
                ( 'CD', 'COD', 'Congo (Democratic Republic of the)', 'Congolese'),
                ( 'CK', 'COK', 'Cook Islands', 'Cook Island'),
                ( 'CR', 'CRI', 'Costa Rica', 'Costa Rican'),
                ( 'CI', 'CIV', 'Côte d\'Ivoire', 'Ivorian'),
                ( 'HR', 'HRV', 'Croatia', 'Croatian'),
                ( 'CU', 'CUB', 'Cuba', 'Cuban'),
                ( 'CW', 'CUW', 'Curaçao', 'Curaçaoan'),
                ( 'CY', 'CYP', 'Cyprus', 'Cypriot'),
                ( 'CZ', 'CZE', 'Czech Republic', 'Czech'),
                ( 'DK', 'DNK', 'Denmark', 'Danish'),
                ( 'DJ', 'DJI', 'Djibouti', 'Djiboutian'),
                ( 'DM', 'DMA', 'Dominica', 'Dominican'),
                ( 'DO', 'DOM', 'Dominican Republic', 'Dominican'),
                ( 'EC', 'ECU', 'Ecuador', 'Ecuadorian'),
                ( 'EG', 'EGY', 'Egypt', 'Egyptian'),
                ( 'SV', 'SLV', 'El Salvador', 'Salvadoran'),
                ( 'GQ', 'GNQ', 'Equatorial Guinea', 'Equatorial Guinean Equatoguinean'),
                ( 'ER', 'ERI', 'Eritrea', 'Eritrean'),
                ( 'EE', 'EST', 'Estonia', 'Estonian'),
                ( 'ET', 'ETH', 'Ethiopia', 'Ethiopian'),
                ( 'FK', 'FLK', 'Falkland Islands (Malvinas)', 'Falkland Island'),
                ( 'FO', 'FRO', 'Faroe Islands', 'Faroese'),
                ( 'FJ', 'FJI', 'Fiji', 'Fijian'),
                ( 'FI', 'FIN', 'Finland', 'Finnish'),
                ( 'FR', 'FRA', 'France', 'French'),
                ( 'GF', 'GUF', 'French Guiana', 'French Guianese'),
                ( 'PF', 'PYF', 'French Polynesia', 'French Polynesian'),
                ( 'TF', 'ATF', 'French Southern Territories', 'French Southern Territories'),
                ( 'GA', 'GAB', 'Gabon', 'Gabonese'),
                ( 'GM', 'GMB', 'Gambia', 'Gambian'),
                ( 'GE', 'GEO', 'Georgia', 'Georgian'),
                ( 'DE', 'DEU', 'Germany', 'German'),
                ( 'GH', 'GHA', 'Ghana', 'Ghanaian'),
                ( 'GI', 'GIB', 'Gibraltar', 'Gibraltar'),
                ( 'GR', 'GRC', 'Greece', 'Greek Hellenic'),
                ( 'GL', 'GRL', 'Greenland', 'Greenlandic'),
                ( 'GD', 'GRD', 'Grenada', 'Grenadian'),
                ( 'GP', 'GLP', 'Guadeloupe', 'Guadeloupe'),
                ( 'GU', 'GUM', 'Guam', 'Guamanian, Guambat'),
                ( 'GT', 'GTM', 'Guatemala', 'Guatemalan'),
                ( 'GG', 'GGY', 'Guernsey', 'Channel Island'),
                ( 'GN', 'GIN', 'Guinea', 'Guinean'),
                ( 'GW', 'GNB', 'Guinea-Bissau', 'Bissau-Guinean'),
                ( 'GY', 'GUY', 'Guyana', 'Guyanese'),
                ( 'HT', 'HTI', 'Haiti', 'Haitian'),
                ( 'HM', 'HMD', 'Heard Island and McDonald Islands', 'Heard Island or McDonald Islands'),
                ( 'VA', 'VAT', 'Vatican City State', 'Vatican'),
                ( 'HN', 'HND', 'Honduras', 'Honduran'),
                ( 'HK', 'HKG', 'Hong Kong', 'Hong Kong Hong Kongese'),
                ( 'HU', 'HUN', 'Hungary', 'Hungarian Magyar'),
                ( 'IS', 'ISL', 'Iceland', 'Icelandic'),
                ( 'IN', 'IND', 'India', 'Indian'),
                ( 'ID', 'IDN', 'Indonesia', 'Indonesian'),
                ( 'IR', 'IRN', 'Iran', 'Iranian Persian'),
                ( 'IQ', 'IRQ', 'Iraq', 'Iraqi'),
                ( 'IE', 'IRL', 'Ireland', 'Irish'),
                ( 'IM', 'IMN', 'Isle of Man', 'Manx'),
                ( 'IT', 'ITA', 'Italy', 'Italian'),
                ( 'JM', 'JAM', 'Jamaica', 'Jamaican'),
                ( 'JP', 'JPN', 'Japan', 'Japanese'),
                ( 'JE', 'JEY', 'Jersey', 'Channel Island'),
                ( 'JO', 'JOR', 'Jordan', 'Jordanian'),
                ( 'KZ', 'KAZ', 'Kazakhstan', 'Kazakhstani Kazakh'),
                ( 'KE', 'KEN', 'Kenya', 'Kenyan'),
                ( 'KI', 'KIR', 'Kiribati', 'I-Kiribati'),
                ( 'KP', 'PRK', 'Korea (Democratic People\'s Republic of)', 'North Korean'),
                ( 'KR', 'KOR', 'Korea (Republic of)', 'South Korean'),
                ( 'KW', 'KWT', 'Kuwait', 'Kuwaiti'),
                ( 'KG', 'KGZ', 'Kyrgyzstan', 'Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz'),
                ( 'LA', 'LAO', 'Lao People\'s Democratic Republic', 'Lao, Laotian'),
                ( 'LV', 'LVA', 'Latvia', 'Latvian'),
                ( 'LB', 'LBN', 'Lebanon', 'Lebanese'),
                ( 'LS', 'LSO', 'Lesotho', 'Basotho'),
                ( 'LR', 'LBR', 'Liberia', 'Liberian'),
                ( 'LY', 'LBY', 'Libya', 'Libyan'),
                ( 'LI', 'LIE', 'Liechtenstein', 'Liechtenstein'),
                ( 'LT', 'LTU', 'Lithuania', 'Lithuanian'),
                ( 'LU', 'LUX', 'Luxembourg', 'Luxembourg, Luxembourgish'),
                ( 'MO', 'MAC', 'Macao', 'Macanese, Chinese'),
                ( 'MK', 'MKD', 'Macedonia (the former Yugoslav Republic of)', 'Macedonian'),
                ( 'MG', 'MDG', 'Madagascar', 'Malagasy'),
                ( 'MW', 'MWI', 'Malawi', 'Malawian'),
                ( 'MY', 'MYS', 'Malaysia', 'Malaysian'),
                ( 'MV', 'MDV', 'Maldives', 'Maldivian'),
                ( 'ML', 'MLI', 'Mali', 'Malian, Malinese'),
                ( 'MT', 'MLT', 'Malta', 'Maltese'),
                ( 'MH', 'MHL', 'Marshall Islands', 'Marshallese'),
                ( 'MQ', 'MTQ', 'Martinique', 'Martiniquais, Martinican'),
                ( 'MR', 'MRT', 'Mauritania', 'Mauritanian'),
                ( 'MU', 'MUS', 'Mauritius', 'Mauritian'),
                ( 'YT', 'MYT', 'Mayotte', 'Mahoran'),
                ( 'MX', 'MEX', 'Mexico', 'Mexican'),
                ( 'FM', 'FSM', 'Micronesia (Federated States of)', 'Micronesian'),
                ( 'MD', 'MDA', 'Moldova (Republic of)', 'Moldovan'),
                ( 'MC', 'MCO', 'Monaco', 'Monégasque, Monacan'),
                ( 'MN', 'MNG', 'Mongolia', 'Mongolian'),
                ( 'ME', 'MNE', 'Montenegro', 'Montenegrin'),
                ( 'MS', 'MSR', 'Montserrat', 'Montserratian'),
                ( 'MA', 'MAR', 'Morocco', 'Moroccan'),
                ( 'MZ', 'MOZ', 'Mozambique', 'Mozambican'),
                ( 'MM', 'MMR', 'Myanmar', 'Burmese'),
                ( 'NA', 'NAM', 'Namibia', 'Namibian'),
                ( 'NR', 'NRU', 'Nauru', 'Nauruan'),
                ( 'NP', 'NPL', 'Nepal', 'Nepali, Nepalese'),
                ( 'NL', 'NLD', 'Netherlands', 'Dutch, Netherlandic'),
                ( 'NC', 'NCL', 'New Caledonia', 'New Caledonian'),
                ( 'NZ', 'NZL', 'New Zealand', 'New Zealand, NZ'),
                ( 'NI', 'NIC', 'Nicaragua', 'Nicaraguan'),
                ( 'NE', 'NER', 'Niger', 'Nigerien'),
                ( 'NG', 'NGA', 'Nigeria', 'Nigerian'),
                ( 'NU', 'NIU', 'Niue', 'Niuean'),
                ( 'NF', 'NFK', 'Norfolk Island', 'Norfolk Island'),
                ( 'MP', 'MNP', 'Northern Mariana Islands', 'Northern Marianan'),
                ( 'NO', 'NOR', 'Norway', 'Norwegian'),
                ( 'OM', 'OMN', 'Oman', 'Omani'),
                ( 'PK', 'PAK', 'Pakistan', 'Pakistani'),
                ( 'PW', 'PLW', 'Palau', 'Palauan'),
                ( 'PS', 'PSE', 'Palestine, State of', 'Palestinian'),
                ( 'PA', 'PAN', 'Panama', 'Panamanian'),
                ( 'PG', 'PNG', 'Papua New Guinea', 'Papua New Guinean Papuan'),
                ( 'PY', 'PRY', 'Paraguay', 'Paraguayan'),
                ( 'PE', 'PER', 'Peru', 'Peruvian'),
                ( 'PH', 'PHL', 'Philippines', 'Philippine Filipino'),
                ( 'PN', 'PCN', 'Pitcairn', 'Pitcairn Island'),
                ( 'PL', 'POL', 'Poland', 'Polish'),
                ( 'PT', 'PRT', 'Portugal', 'Portuguese'),
                ( 'PR', 'PRI', 'Puerto Rico', 'Puerto Rican'),
                ( 'QA', 'QAT', 'Qatar', 'Qatari'),
                ( 'RE', 'REU', 'Réunion', 'Réunionese, Réunionnais'),
                ( 'RO', 'ROU', 'Romania', 'Romanian'),
                ( 'RU', 'RUS', 'Russian Federation', 'Russian'),
                ( 'RW', 'RWA', 'Rwanda', 'Rwandan'),
                ( 'BL', 'BLM', 'Saint Barthélemy', 'Barthélemois'),
                ( 'SH', 'SHN', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Helenian'),
                ( 'KN', 'KNA', 'Saint Kitts and Nevis', 'Kittitian or Nevisian'),
                ( 'LC', 'LCA', 'Saint Lucia', 'Saint Lucian'),
                ( 'MF', 'MAF', 'Saint Martin (French part)', 'Saint-Martinoise'),
                ( 'PM', 'SPM', 'Saint Pierre and Miquelon', 'Saint-Pierrais or Miquelonnais'),
                ( 'VC', 'VCT', 'Saint Vincent and the Grenadines', 'Saint Vincentian, Vincentian'),
                ( 'WS', 'WSM', 'Samoa', 'Samoan'),
                ( 'SM', 'SMR', 'San Marino', 'Sammarinese'),
                ( 'ST', 'STP', 'Sao Tome and Principe', 'São Toméan'),
                ( 'SA', 'SAU', 'Saudi Arabia', 'Saudi, Saudi Arabian'),
                ( 'SN', 'SEN', 'Senegal', 'Senegalese'),
                ( 'RS', 'SRB', 'Serbia', 'Serbian'),
                ( 'SC', 'SYC', 'Seychelles', 'Seychellois'),
                ( 'SL', 'SLE', 'Sierra Leone', 'Sierra Leonean'),
                ( 'SG', 'SGP', 'Singapore', 'Singaporean'),
                ( 'SX', 'SXM', 'Sint Maarten (Dutch part)', 'Sint Maarten'),
                ( 'SK', 'SVK', 'Slovakia', 'Slovak'),
                ( 'SI', 'SVN', 'Slovenia', 'Slovenian, Slovene'),
                ( 'SB', 'SLB', 'Solomon Islands', 'Solomon Island'),
                ( 'SO', 'SOM', 'Somalia', 'Somali, Somalian'),
                ( 'ZA', 'ZAF', 'South Africa', 'South African'),
                ( 'GS', 'SGS', 'South Georgia and the South Sandwich Islands', 'South Georgia or South Sandwich Islands'),
                ( 'SS', 'SSD', 'South Sudan', 'South Sudanese'),
                ( 'ES', 'ESP', 'Spain', 'Spanish'),
                ( 'LK', 'LKA', 'Sri Lanka', 'Sri Lankan'),
                ( 'SD', 'SDN', 'Sudan', 'Sudanese'),
                ( 'SR', 'SUR', 'Suriname', 'Surinamese'),
                ( 'SJ', 'SJM', 'Svalbard and Jan Mayen', 'Svalbard'),
                ( 'SZ', 'SWZ', 'Swaziland', 'Swazi'),
                ( 'SE', 'SWE', 'Sweden', 'Swedish'),
                ( 'CH', 'CHE', 'Switzerland', 'Swiss'),
                ( 'SY', 'SYR', 'Syrian Arab Republic', 'Syrian'),
                ( 'TW', 'TWN', 'Taiwan, Province of China', 'Chinese, Taiwanese'),
                ( 'TJ', 'TJK', 'Tajikistan', 'Tajikistani'),
                ( 'TZ', 'TZA', 'Tanzania, United Republic of', 'Tanzanian'),
                ( 'TH', 'THA', 'Thailand', 'Thai'),
                ( 'TL', 'TLS', 'Timor-Leste', 'Timorese'),
                ( 'TG', 'TGO', 'Togo', 'Togolese'),
                ( 'TK', 'TKL', 'Tokelau', 'Tokelauan'),
                ( 'TO', 'TON', 'Tonga', 'Tongan'),
                ( 'TT', 'TTO', 'Trinidad and Tobago', 'Trinidadian or Tobagonian'),
                ( 'TN', 'TUN', 'Tunisia', 'Tunisian'),
                ( 'TR', 'TUR', 'Turkey', 'Turkish'),
                ( 'TM', 'TKM', 'Turkmenistan', 'Turkmen'),
                ( 'TC', 'TCA', 'Turks and Caicos Islands', 'Turks and Caicos Island'),
                ( 'TV', 'TUV', 'Tuvalu', 'Tuvaluan'),
                ( 'UG', 'UGA', 'Uganda', 'Ugandan'),
                ( 'UA', 'UKR', 'Ukraine', 'Ukrainian'),
                ( 'AE', 'ARE', 'United Arab Emirates', 'Emirati, Emirian, Emiri'),
                ( 'GB', 'GBR', 'United Kingdom of Great Britain and Northern Ireland', 'British, UK'),
                ( 'UM', 'UMI', 'United States Minor Outlying Islands', 'American'),
                ( 'US', 'USA', 'United States of America', 'American'),
                ( 'UY', 'URY', 'Uruguay', 'Uruguayan'),
                ( 'UZ', 'UZB', 'Uzbekistan', 'Uzbekistani, Uzbek'),
                ( 'VU', 'VUT', 'Vanuatu', 'Ni-Vanuatu, Vanuatuan'),
                ( 'VE', 'VEN', 'Venezuela (Bolivarian Republic of)', 'Venezuelan'),
                ( 'VN', 'VNM', 'Vietnam', 'Vietnamese'),
                ( 'VG', 'VGB', 'Virgin Islands (British)', 'British Virgin Island'),
                ( 'VI', 'VIR', 'Virgin Islands (U.S.)', 'U.S. Virgin Island'),
                ( 'WF', 'WLF', 'Wallis and Futuna', 'Wallis and Futuna, Wallisian or Futunan'),
                ( 'EH', 'ESH', 'Western Sahara', 'Sahrawi, Sahrawian, Sahraouian'),
                ( 'YE', 'YEM', 'Yemen', 'Yemeni'),
                ( 'ZM', 'ZMB', 'Zambia', 'Zambian'),
                ( 'ZW', 'ZWE', 'Zimbabwe', 'Zimbabwean')
                ");
    }
}
