<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::insert("INSERT INTO `payes` (`id`, `name`, `created_at`, `updated_at`) VALUES
        (1, 'Maroc', NULL, NULL),
        (2, 'Albanie', NULL, NULL),
        (3, 'Algérie', NULL, NULL),
        (4, 'Samoa orientales (téritoire USA)', NULL, NULL),
        (5, 'Andorre', NULL, NULL),
        (6, 'Angola', NULL, NULL),
        (7, 'Anguilla', NULL, NULL),
        (8, 'Antarctique', NULL, NULL),
        (9, 'Antigua-et-Barbuda', NULL, NULL),
        (10, 'Argentine', NULL, NULL),
        (11, 'Arménie', NULL, NULL),
        (12, 'Aruba', NULL, NULL),
        (13, 'Australie', NULL, NULL),
        (14, 'Autriche', NULL, NULL),
        (15, 'Azerbaïdjan', NULL, NULL),
        (16, 'Bahamas', NULL, NULL),
        (17, 'Bahreïn', NULL, NULL),
        (18, 'Bangladesh', NULL, NULL),
        (19, 'Barbade', NULL, NULL),
        (20, 'Bélarus', NULL, NULL),
        (21, 'Belgique', NULL, NULL),
        (22, 'Bélize', NULL, NULL),
        (23, 'Bénin', NULL, NULL),
        (24, 'Bermudes', NULL, NULL),
        (25, 'Bhoutan', NULL, NULL),
        (26, 'Bolivie', NULL, NULL),
        (27, 'Bosnie-Herzégovine', NULL, NULL),
        (28, 'Botswana', NULL, NULL),
        (29, 'Bouvet (Île) (téritoire norvégien)', NULL, NULL),
        (30, 'Brésil', NULL, NULL),
        (31, 'Territoire britannique de l\'Océan Indien', NULL, NULL),
        (32, 'Brunéi Darussalam', NULL, NULL),
        (33, 'Bulgarie', NULL, NULL),
        (34, 'Burkina Faso', NULL, NULL),
        (35, 'Burundi', NULL, NULL),
        (36, 'Cambodge', NULL, NULL),
        (37, 'Cameroun', NULL, NULL),
        (38, 'Canada', NULL, NULL),
        (39, 'Cap Vert', NULL, NULL),
        (40, 'Caïmans (Îles)', NULL, NULL),
        (41, 'République Centrafricaine', NULL, NULL),
        (42, 'Tchad', NULL, NULL),
        (43, 'Chili', NULL, NULL),
        (44, 'Chine', NULL, NULL),
        (45, 'Christmas (Île) (téritoire australie)', NULL, NULL),
        (46, 'Cocos / Keeling (Îles) téritoire australien', NULL, NULL),
        (47, 'Colombie', NULL, NULL),
        (48, 'Comores', NULL, NULL),
        (49, 'Congo', NULL, NULL),
        (50, 'République Démocratique du Congo', NULL, NULL),
        (51, 'Cook (Îles)', NULL, NULL),
        (52, 'Costa Rica', NULL, NULL),
        (53, 'Côte D\'Ivoire', NULL, NULL),
        (54, 'Croatie', NULL, NULL),
        (55, 'Cuba', NULL, NULL),
        (56, 'Chypre', NULL, NULL),
        (57, 'République Tchèque', NULL, NULL),
        (58, 'Danemark', NULL, NULL),
        (59, 'Djibouti', NULL, NULL),
        (60, 'Dominique', NULL, NULL),
        (61, 'République Dominicaine', NULL, NULL),
        (62, 'Timor-Oriental', NULL, NULL),
        (63, 'Equateur', NULL, NULL),
        (64, 'Egypte', NULL, NULL),
        (65, 'El Salvador', NULL, NULL),
        (66, 'Guinée Equatoriale', NULL, NULL),
        (67, 'Erythrée', NULL, NULL),
        (68, 'Estonie', NULL, NULL),
        (69, 'Ethiopie', NULL, NULL),
        (70, 'Falkland / Malouines (Îles) téritoire royaum uni', NULL, NULL),
        (71, 'Féroé (Îles) Danoise', NULL, NULL),
        (72, 'Fidji', NULL, NULL),
        (73, 'Finlande', NULL, NULL),
        (74, 'France', NULL, NULL),
        (75, 'France métropolitaine', NULL, NULL),
        (76, 'Guyane française', NULL, NULL),
        (77, 'Polynésie française', NULL, NULL),
        (78, 'Territoires Antarctiques français', NULL, NULL),
        (79, 'Gabon', NULL, NULL),
        (80, 'Gambie', NULL, NULL),
        (81, 'Géorgie', NULL, NULL),
        (82, 'Allemagne', NULL, NULL),
        (83, 'Ghana', NULL, NULL),
        (84, 'Gibraltar', NULL, NULL),
        (85, 'Grèce', NULL, NULL),
        (86, 'Groënland (téritoire danois)', NULL, NULL),
        (87, 'Grenade', NULL, NULL),
        (88, 'Guadeloupe  (téritoire Français)', NULL, NULL),
        (89, 'Guam (USA)', NULL, NULL),
        (90, 'Guatemala', NULL, NULL),
        (91, 'Guinée', NULL, NULL),
        (92, 'Guinée-Bissau', NULL, NULL),
        (93, 'Guyana', NULL, NULL),
        (94, 'Haïti', NULL, NULL),
        (95, 'Territoire des Îles Heard et McDonald (Australie)', NULL, NULL),
        (96, 'Vatican', NULL, NULL),
        (97, 'Honduras', NULL, NULL),
        (98, 'Hong Kong', NULL, NULL),
        (99, 'Hongrie', NULL, NULL),
        (100, 'Islande', NULL, NULL),
        (101, 'Inde', NULL, NULL),
        (102, 'Indonésie', NULL, NULL),
        (103, 'Iran (République islamique d\'Iran)', NULL, NULL),
        (104, 'Iraq', NULL, NULL),
        (105, 'Irlande', NULL, NULL),
        (107, 'Italie', NULL, NULL),
        (108, 'Jamaïque', NULL, NULL),
        (109, 'Japon', NULL, NULL),
        (110, 'Jordanie', NULL, NULL),
        (111, 'Kazakstan', NULL, NULL),
        (112, 'Kenya', NULL, NULL),
        (113, 'Kiribati', NULL, NULL),
        (114, 'Corée (République populaire démocratique du)', NULL, NULL),
        (115, 'Corée (République démocratique du)', NULL, NULL),
        (116, 'Koweït', NULL, NULL),
        (117, 'Kyrgyzstan', NULL, NULL),
        (118, 'Lao (République populaire démocratique du)', NULL, NULL),
        (119, 'Lettonie', NULL, NULL),
        (120, 'Liban', NULL, NULL),
        (121, 'Lesotho', NULL, NULL),
        (122, 'Libéria', NULL, NULL),
        (123, 'Libye', NULL, NULL),
        (124, 'Liechtenstein', NULL, NULL),
        (125, 'Lithuanie', NULL, NULL),
        (126, 'Luxembourg', NULL, NULL),
        (127, 'Chine, région administrative spéciale de Macao', NULL, NULL),
        (128, 'Macédoine (ancienne République yougoslave de)', NULL, NULL),
        (129, 'Madagascar', NULL, NULL),
        (130, 'Malawi', NULL, NULL),
        (131, 'Malaisie', NULL, NULL),
        (132, 'Maldives', NULL, NULL),
        (133, 'Mali', NULL, NULL),
        (134, 'Malte', NULL, NULL),
        (135, 'Marshall (Îles)', NULL, NULL),
        (136, 'Martinique (téritoire Français)', NULL, NULL),
        (137, 'Mauritanie', NULL, NULL),
        (138, 'Maurice', NULL, NULL),
        (139, 'Mayotte  (téritoire Français)', NULL, NULL),
        (140, 'Mexique', NULL, NULL),
        (141, 'Micronésie (Etats fédérés de)', NULL, NULL),
        (142, 'Moldavie', NULL, NULL),
        (143, 'Monaco', NULL, NULL),
        (144, 'Mongolie', NULL, NULL),
        (145, 'Montserrat', NULL, NULL),
        (146, 'Maroc', NULL, NULL),
        (147, 'Mozambique', NULL, NULL),
        (148, 'Myanmar', NULL, NULL),
        (149, 'Namibie', NULL, NULL),
        (150, 'Nauru', NULL, NULL),
        (151, 'Népal', NULL, NULL),
        (152, 'Pays-Bas', NULL, NULL),
        (153, 'Antilles néerlandaises', NULL, NULL),
        (154, 'Nouvelle-Calédonie', NULL, NULL),
        (155, 'Nouvelle-Zélande', NULL, NULL),
        (156, 'Nicaragua', NULL, NULL),
        (157, 'Niger', NULL, NULL),
        (158, 'Nigéria', NULL, NULL),
        (159, 'Niue', NULL, NULL),
        (160, 'Norfolk (Île) (téritoire australie)', NULL, NULL),
        (161, 'Mariannes (Îles)', NULL, NULL),
        (162, 'Norvège', NULL, NULL),
        (163, 'Oman', NULL, NULL),
        (164, 'Pakistan', NULL, NULL),
        (165, 'Palaos', NULL, NULL),
        (166, 'Panama', NULL, NULL),
        (167, 'Papouasie Nouvelle-Guinée', NULL, NULL),
        (168, 'Paraguay', NULL, NULL),
        (169, 'Pérou', NULL, NULL),
        (170, 'Philippines', NULL, NULL),
        (171, 'Pitcaïrn ( territoire britannique)', NULL, NULL),
        (172, 'Pologne', NULL, NULL),
        (173, 'Portugal', NULL, NULL),
        (174, 'Porto Rico', NULL, NULL),
        (175, 'Qatar', NULL, NULL),
        (176, 'Réunion (téritoire Français)', NULL, NULL),
        (177, 'Roumanie', NULL, NULL),
        (178, 'Russie (Fédération de)', NULL, NULL),
        (179, 'Ruwanda', NULL, NULL),
        (180, 'Saint Kitts et Nevis', NULL, NULL),
        (181, 'Sainte Lucie', NULL, NULL),
        (182, 'Saint Vincent et Grenadines', NULL, NULL),
        (183, 'Samoa', NULL, NULL),
        (184, 'Saint-Marin', NULL, NULL),
        (185, 'Sao Tomé et Principe', NULL, NULL),
        (186, 'Arabie Séoudite', NULL, NULL),
        (187, 'Sénégal', NULL, NULL),
        (188, 'Seychelles', NULL, NULL),
        (189, 'Sierra Léone', NULL, NULL),
        (190, 'Singapour', NULL, NULL),
        (191, 'Slovaquie', NULL, NULL),
        (192, 'Slovénie', NULL, NULL),
        (193, 'Salomon (Îles)', NULL, NULL),
        (194, 'Somalie', NULL, NULL),
        (195, 'Afrique du Sud', NULL, NULL),
        (196, 'Géorgie du Sud et îles Sandwich du Sud ( territoire britannique)', NULL, NULL),
        (197, 'Espagne', NULL, NULL),
        (198, 'Sri Lanka', NULL, NULL),
        (199, 'Ste Hélène ( territoire britannique)', NULL, NULL),
        (200, 'St. Pierre et Miquelon (téritoire Français)', NULL, NULL),
        (201, 'Soudan', NULL, NULL),
        (202, 'Surinam', NULL, NULL),
        (203, 'Svalbard et Jan Mayen (Îles) territoire de la Norvège', NULL, NULL),
        (204, 'Swaziland (Istiwanie)', NULL, NULL),
        (205, 'Suède', NULL, NULL),
        (206, 'Suisse', NULL, NULL),
        (207, 'Syrie (République arabe syrienne)', NULL, NULL),
        (208, 'Taïwan (officiellement la république de Chine) ', NULL, NULL),
        (209, 'Tadjikistan', NULL, NULL),
        (210, 'Tanzanie', NULL, NULL),
        (211, 'Thaïlande', NULL, NULL),
        (212, 'Togo', NULL, NULL),
        (213, 'Tokélaou', NULL, NULL),
        (214, 'Tonga', NULL, NULL),
        (215, 'Trinidad et Tobago', NULL, NULL),
        (216, 'Tunisie', NULL, NULL),
        (217, 'Turquie', NULL, NULL),
        (218, 'Turkménistan', NULL, NULL),
        (219, 'Îles Turques et Caïques', NULL, NULL),
        (220, 'Tuvalu', NULL, NULL),
        (221, 'Ouganda', NULL, NULL),
        (222, 'Ukraine', NULL, NULL),
        (223, 'Emirats Arabes Unis', NULL, NULL),
        (224, 'Royaume-Uni', NULL, NULL),
        (225, 'Etats-Unis d\'Amérique', NULL, NULL),
        (226, 'Territoires non incorporés des États-Unis ', NULL, NULL),
        (227, 'Uruguay', NULL, NULL),
        (228, 'Ouzbékistan', NULL, NULL),
        (229, 'Vanuatu', NULL, NULL),
        (230, 'Vénézuela', NULL, NULL),
        (231, 'Viet Nam', NULL, NULL),
        (232, 'Vierges (Îles) - RU', NULL, NULL),
        (233, 'Vierges (Îles) - EU (USA)', NULL, NULL),
        (234, 'Wallis et Futuna (Îles) ( territoire français )', NULL, NULL),
        (236, 'Yemen', NULL, NULL),
        (237, 'Yougoslavie', NULL, NULL),
        (238, 'Zambie', NULL, NULL),
        (239, 'Zimbabwe', NULL, NULL),
        (240, 'Haut volta', NULL, NULL),
        (241, 'Sud-Soudan', NULL, NULL),
        (242, 'Curaçao', NULL, NULL),
        (243, 'Îles Vierges britanniques', NULL, NULL),
        (245, 'Monténégro', NULL, NULL),
        (246, 'Saint-Martin (partie néerlandaise)', NULL, NULL),
        (247, 'Saint-Siège', NULL, NULL),
        (248, 'Serbie', NULL, NULL),
        (500, 'Palestine', NULL, NULL),
        (900, 'Pays non spécifié (afrique)', NULL, NULL),
        (999, 'Pays non spécifié', NULL, NULL);
        ");
    }
}
